# Generated by Django 3.2.12 on 2022-10-12 08:26

from django.db import migrations
import os
from django.contrib.auth.models import Group, Permission
import json
from pathlib import Path
from django.core.exceptions import ObjectDoesNotExist


def load_roles(apps, schema_editor):
    path = Path(Path.cwd(), 'perms_app', 'fixtures', 'auth_groups.json')
    with open(path) as file:
        data = json.load(file)
        for elem in data:
            group = Group.objects.create(name=elem['fields']['name'])
            # group.permissions.set(elem['fields']['permissions']) ###Не работает, хотя по документации так нужно
            group.save()


###Доп вариант вынес в отдельную функцию и сделал добавление пермишинов напрямую из существующих
def load_perms_for_roles(apps, schema_editor):
    permissions_list = Permission.objects.all() ###Выдает пустой queryset. Хз почему

    path = Path(Path.cwd(), 'perms_app', 'fixtures', 'auth_groups.json')
    with open(path) as file:
        data = json.load(file)
        for elem in data:
            perms_for_add = list()
            for perm_id in elem['fields']['permissions']:
                for perm in permissions_list:
                    if perm_id == perm['id']:
                        perms_for_add.append(perm)
            group = Group.objects.get(pk=elem['pk'])
            group.permissions.set(perms_for_add)
            group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perms_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_roles),
        migrations.RunPython(load_perms_for_roles)
    ]
