stages:
  - code quality

default:
  image: python:3.8.12
  tags:
    - students
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - pip install -r requirements/dev.txt

#isort:
#  stage: code quality
#  script:
#    - isort market/ --src=market/ -c --diff

flake8:
  stage: code quality
  script:
    - flake8 market

linter:
  stage: code quality
  script:
    - pylint --rcfile=.pylintrc market/*
