# Generated by Django 3.2.12 on 2022-10-20 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGoodProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.FloatField(verbose_name='диагональ экрана')),
                ('processor', models.CharField(max_length=30, verbose_name='процессор')),
                ('ram', models.IntegerField(verbose_name='оперативная память')),
                ('ssd', models.BooleanField(verbose_name='наличие SSD')),
            ],
        ),
        migrations.CreateModel(
            name='TestGoodTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='тип товара')),
            ],
        ),
        migrations.CreateModel(
            name='TestGoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя товара')),
                ('code', models.CharField(max_length=10, verbose_name='артикул товара')),
                ('good_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compare_app.testgoodprofilemodel', verbose_name='профиль товара')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare_app.testgoodtypemodel', verbose_name='тип товара')),
            ],
        ),
        migrations.CreateModel(
            name='CompareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare_app.testgoodmodel', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'товар для сравнения',
                'verbose_name_plural': 'товары для сравнения',
            },
        ),
    ]
