# Generated by Django 3.2.12 on 2022-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgoodprofilemodel',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='testgoodprofilemodel',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='testgoodprofilemodel',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='testgoodprofilemodel',
            name='ssd',
        ),
        migrations.AddField(
            model_name='testgoodprofilemodel',
            name='battery_charging_time',
            field=models.IntegerField(default=None, verbose_name='время зарядки от сети'),
        ),
        migrations.AddField(
            model_name='testgoodprofilemodel',
            name='battery_working_time',
            field=models.IntegerField(default=None, verbose_name='время работы от батареи'),
        ),
        migrations.AddField(
            model_name='testgoodprofilemodel',
            name='cpu_frequency',
            field=models.FloatField(default=None, verbose_name='частота процессора'),
        ),
        migrations.AddField(
            model_name='testgoodprofilemodel',
            name='price',
            field=models.IntegerField(default=None, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='testgoodprofilemodel',
            name='rating',
            field=models.IntegerField(default=None, verbose_name='рейтинг товара'),
        ),
        migrations.AddField(
            model_name='testgoodprofilemodel',
            name='usb_ports',
            field=models.IntegerField(default=None, verbose_name='количество разъемов usb'),
        ),
    ]
