# Generated by Django 3.2.12 on 2022-10-20 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0002_auto_20221020_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparemodel',
            name='good',
        ),
        migrations.AddField(
            model_name='comparemodel',
            name='goods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
