# Generated by Django 3.2.12 on 2022-10-21 07:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0004_comparemodel_type_for_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgoodmodel',
            name='paths_to_good_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['assets/img/content/home/card.jpg'], size=None),
            preserve_default=False,
        ),
    ]
