# Generated by Django 3.2.12 on 2022-10-24 09:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0005_testgoodmodel_paths_to_good_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя товара')),
                ('paths_to_good_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compare_app.testcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='TestSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='код спецификации')),
                ('name', models.CharField(max_length=30, verbose_name='название спецификации')),
                ('uom', models.CharField(max_length=30, verbose_name='хз что это')),
            ],
            options={
                'verbose_name': 'спецификация',
                'verbose_name_plural': 'спецификации',
            },
        ),
        migrations.CreateModel(
            name='TestSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='значение спецификации')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compare_app.testproduct', verbose_name='товар')),
                ('specification', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compare_app.testspecification', verbose_name='спецификация')),
            ],
            options={
                'verbose_name': 'спецификация товара',
                'verbose_name_plural': 'спецификации товара',
            },
        ),
        migrations.RemoveField(
            model_name='comparemodel',
            name='type_for_compare',
        ),
        migrations.DeleteModel(
            name='TestGoodModel',
        ),
        migrations.DeleteModel(
            name='TestGoodProfileModel',
        ),
        migrations.DeleteModel(
            name='TestGoodTypeModel',
        ),
        migrations.AddField(
            model_name='comparemodel',
            name='category_for_compare',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compare_app.testcategory', verbose_name='категория товаров для сравнения'),
        ),
    ]
