# Generated by Django 3.2.12 on 2022-10-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0006_auto_20221024_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testspecificationvalue',
            name='specification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compare_app.testspecification', verbose_name='спецификация'),
        ),
    ]
