# Generated by Django 3.2.12 on 2022-10-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0007_alter_testspecificationvalue_specification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompareModel',
        ),
    ]
