# Generated by Django 3.2.12 on 2023-02-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0008_delete_comparemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testspecificationvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='testspecificationvalue',
            name='specification',
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
        migrations.DeleteModel(
            name='TestProduct',
        ),
        migrations.DeleteModel(
            name='TestSpecification',
        ),
        migrations.DeleteModel(
            name='TestSpecificationValue',
        ),
    ]
