# Generated by Django 3.2.12 on 2023-02-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authshoppingcart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Цена за товар'),
        ),
    ]
