# Generated by Django 3.2.12 on 2023-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='название сайта')),
                ('phone_number1', models.CharField(max_length=255, verbose_name='номер телефона 1')),
                ('phone_number2', models.CharField(max_length=255, verbose_name='номер телефона 2')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('banner_number', models.PositiveSmallIntegerField(verbose_name='количество баннеров')),
                ('stopping_sales', models.BooleanField(default=False, verbose_name='остановка продаж')),
                ('banner_cache_time', models.PositiveIntegerField(verbose_name='кэш баннеров')),
                ('total_cache_time', models.PositiveIntegerField(verbose_name='общий кэш')),
                ('seller_cache_time', models.PositiveIntegerField(verbose_name='время кэша продавцов')),
                ('sellers_products_top_cache_time', models.PositiveIntegerField(verbose_name='время кэша продавцов')),
                ('sellers_products_top_number', models.PositiveSmallIntegerField(verbose_name='количество популярных товаров продавца')),
                ('common_products_top_number', models.PositiveSmallIntegerField(verbose_name='количество популярных товаров главной страницы')),
                ('ordinary_delivery_cost', models.PositiveIntegerField(verbose_name='стоимость обычной доставки')),
                ('min_amount_for_free_delivery', models.PositiveIntegerField(verbose_name='минимальная сумма для бесплатной обычной доставки')),
                ('express_delivery_cost', models.PositiveIntegerField(verbose_name='стоимость экспресс доставки')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
