# Generated by Django 3.2.12 on 2022-12-03 15:55

from django.db import migrations

from app_settings.utils import get_settings


def update_settings_data(apps, schema_editor):
    settings_config = get_settings()
    SiteSettings = apps.get_model('app_settings', 'SiteSettings')
    SiteSettings.objects.filter(id=1).update(seller_cache_time=settings_config['seller_cache_time'],
                                             sellers_products_top_cache_time=settings_config[
                                                 'sellers_products_top_cache_time'],
                                             sellers_products_top_number=settings_config['sellers_products_top_number'],
                                             common_products_top_number=settings_config['common_products_top_number'])


class Migration(migrations.Migration):
    dependencies = [
        ('app_settings', '0003_auto_20221203_1555'),
    ]

    operations = [
        migrations.RunPython(update_settings_data),
    ]
