# Generated by Django 3.2.12 on 2023-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_auto_20221203_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='banner_cache_time',
            field=models.PositiveIntegerField(verbose_name='Кэш баннеров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='total_cache_time',
            field=models.PositiveIntegerField(verbose_name='Общий кэш'),
        ),
    ]
