# Generated by Django 3.2.12 on 2023-03-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0006_auto_20230206_2058'),
        ('app_settings', '0006_auto_20230209_1855'),
    ]

    operations = [
    ]
