# Generated by Django 3.2.12 on 2023-03-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0007_merge_0006_auto_20230206_2058_0006_auto_20230209_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='express_delivery_cost',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='стоимость экспресс доставки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_amount_for_free_delivery',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='минимальная сумма для бесплатной обычной доставки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ordinary_delivery_cost',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='стоимость обычной доставки'),
        ),
    ]
