# Generated by Django 3.2.12 on 2023-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product_in_cart',
            field=models.IntegerField(default=0, verbose_name='Количество товара в корзине'),
        ),
    ]
