# Generated by Django 3.2.12 on 2022-11-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
