# Generated by Django 3.2.12 on 2023-01-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
        ('market_app', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(upload_to='seller_files/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='app_login.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название магазина'),
        ),
    ]
