# Generated by Django 3.2.12 on 2023-02-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_auto_20230209_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', max_length=2000, verbose_name='описание'),
        ),
    ]
