# Generated by Django 3.2.12 on 2023-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_auto_20230209_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Картинка категории товаров'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Название картинки категории'),
        ),
    ]
