# Generated by Django 3.2.12 on 2023-02-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0006_auto_20230211_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='market_app.seller', verbose_name='продавец'),
        ),
    ]
