# Generated by Django 3.2.12 on 2023-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FilePathField(blank=True, default=None, null=True, verbose_name='Картинка категории товаров'),
        ),
    ]
