# Generated by Django 3.2.12 on 2023-02-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Картинка категории товаров'),
        ),
    ]
