# Generated by Django 3.2.12 on 2023-02-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_auto_20230206_2058'),
        ('market_app', '0009_auto_20230216_0651'),
    ]

    operations = [
    ]
