# Generated by Django 3.2.12 on 2023-02-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0009_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(max_length=30, verbose_name='название характеристики')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='значение характеристики')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_app.characteristic', verbose_name='связь значение характеристики - характеристика')),
            ],
            options={
                'verbose_name': 'значение характеристик',
                'verbose_name_plural': 'значения характеристик',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, verbose_name='название группы характеристик')),
                ('category', models.ManyToManyField(to='market_app.Category', verbose_name='связь категория - группа характеристик')),
            ],
            options={
                'verbose_name': 'группа характеристик',
                'verbose_name_plural': 'группы характеристик',
            },
        ),
        migrations.AddField(
            model_name='characteristic',
            name='group',
            field=models.ManyToManyField(to='market_app.CharacteristicsGroup', verbose_name='связь группа характеристик - характеристика'),
        ),
    ]
