# Generated by Django 3.2.12 on 2023-02-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0010_auto_20230218_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicvalue',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='market_app.product', verbose_name='связь значение характеристики - продукт'),
        ),
    ]
