# Generated by Django 3.2.12 on 2023-02-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0010_merge_0005_auto_20230206_2058_0009_auto_20230216_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='market_app.product', verbose_name='товар'),
        ),
    ]
