# Generated by Django 3.2.12 on 2023-02-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0011_characteristicvalue_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicvalue',
            name='product',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='market_app.product', verbose_name='связь значение характеристики - продукт'),
        ),
    ]
