# Generated by Django 3.2.12 on 2023-02-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0009_auto_20230216_0651'),
        ('market_app', '0013_alter_characteristicvalue_product'),
    ]

    operations = [
    ]
