# Generated by Django 3.2.12 on 2023-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0014_merge_20230225_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Картинка категории товаров'),
        ),
    ]
