# Generated by Django 3.2.12 on 2023-02-27 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0016_auto_20230227_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='дата начала'),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market_app.discount', verbose_name='скидка'),
        ),
        migrations.DeleteModel(
            name='ProductDiscount',
        ),
    ]
