# Generated by Django 3.2.12 on 2023-03-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0011_alter_sellerproduct_product'),
        ('market_app', '0017_auto_20230227_2158'),
    ]

    operations = [
    ]
