# Generated by Django 3.2.12 on 2023-03-03 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_app', '0018_merge_20230303_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='market_app.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='historyview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
