# Generated by Django 3.2.12 on 2023-03-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0019_auto_20230303_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicvalue',
            name='value',
            field=models.CharField(default='-', max_length=200, verbose_name='значение характеристики'),
        ),
    ]
