# Generated by Django 3.2.12 on 2023-03-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0020_auto_20230304_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='market_app.characteristicsgroup', verbose_name='группа характеристик'),
        ),
        migrations.AlterField(
            model_name='characteristicsgroup',
            name='category',
            field=models.ManyToManyField(related_name='characteristicsgroups', to='market_app.Category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='market_app.characteristic', verbose_name='характеристика'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='market_app.product', verbose_name='продукт'),
        ),
    ]
