# Generated by Django 3.2.12 on 2023-03-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0020_alter_characteristicvalue_value'),
        ('market_app', '0020_auto_20230304_0834'),
    ]

    operations = [
    ]
