# Generated by Django 3.2.12 on 2023-03-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0021_auto_20230306_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_product', to='market_app.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_product', to='market_app.seller', verbose_name='продавец'),
        ),
    ]
