# Generated by Django 3.2.12 on 2023-03-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0022_auto_20230307_1857'),
        ('market_app', '0025_alter_characteristic_group'),
    ]

    operations = [
    ]
