# Generated by Django 3.2.12 on 2023-03-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0026_merge_20230311_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers_products', to='market_app.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers_products', to='market_app.seller', verbose_name='продавец'),
        ),
    ]
